# 异常处理与反射

## 1. 异常处理

开发人员在编写程序时，难免会遇到错误，有的是编写人员疏忽造成的语法错误，有的是程序内部隐含逻辑问题造成的数据错误，还有的是程序运行时与系统的规则冲突造成的系统错误。编写程序时遇到的错误可大致分为 2 类，分别为语法错误和运行时错误。

### 1.1 Python语法错误

语法错误，也就是解析代码时出现的错误。当代码不符合 Python 语法规则时，Python解释器在解析时就会报出 SyntaxError 语法错误，与此同时还会明确指出最早探测到错误的语句。例如：

```python
print "Hello,World!"
```

解释器会报如下错误：

```
SyntaxError: Missing parentheses in call to 'print'
```

这种错误应该在程序运行前就修改正确

### 1.2 Python运行时错误

运行时错误，即程序在语法上都是正确的，但在运行时发生了错误。常见异常类型

|    异常类型    |                   含义                   |
| :------------: | :--------------------------------------: |
| AttributeError |  当试图访问的对象属性不存在时抛出的异常  |
|   IndexError   |       索引超出序列范围会引发此异常       |
|    KeyError    | 字典中查找一个不存在的关键字时引发此异常 |
|   NameError    |  尝试访问一个未声明的变量时，引发此异常  |
|   TypeError    |        不同类型数据之间的无效操作        |

当一个程序发生异常时，代表该程序在执行时出现了非正常的情况，无法再执行下去。默认情况下，程序是要终止的。如果要避免程序退出，可以使用捕获异常的方式获取这个异常的名称，再通过其他的逻辑代码让程序继续运行，这种根据异常做出的逻辑处理叫作异常处理。

### 3. 异常处理

```python
try:
    被检测的代码块
except 异常类型：
    检测到异常，就执行这个位置的逻辑
```

```python
try:
    print('start...')
    print(x)
    print('end...')
# as语法将异常类型的值赋值给变量e，这样我们通过打印e便可以知道错误的原因
except NameError as e: 
    print('异常值为：%s' %e)
print('run other code...')
```

如果我们想分别用不同的逻辑处理，需要用到多分支的except（类似于多分支的elif，从上到下依次匹配，匹配成功一次便不再匹配其他）

```python
try:
    被检测的代码块
except NameError:
    触发NameError时对应的处理逻辑
except IndexError:
    触发IndexError时对应的处理逻辑
except KeyError:
    触发KeyError时对应的处理逻辑
```

如果我们想捕获所有异常并用一种逻辑处理，Python提供了一个万能异常类型Exception

```python
try:
    被检测的代码块
except NameError:
    触发NameError时对应的处理逻辑
except IndexError:
    触发IndexError时对应的处理逻辑
except Exception:
    其他类型的异常统一用此处的逻辑处理
```

在多分支except之后还可以跟一个else（else必须跟在except之后，不能单独存在），只有在被检测的代码块没有触发任何异常的情况下才会执行else的子代码块

```python
try:
    被检测的代码块
except 异常类型1:
    pass
except 异常类型2:
    pass
......
else:
    没有异常发生时执行的代码块
```

此外try还可以与finally连用可以使用try-except-finally的形式，也可以直接使用try-finally的形式。无论被检测的代码块是否触发异常，都会执行finally的子代码块，因此通常在finally的子代码块做一些回收资源的操作，比如关闭打开的文件

```python
try: 
    被检测的代码块 
except 异常类型1: 
    pass 
except 异常类型2: 
    pass 
...... 
else: 
    没有异常发生时执行的代码块 
finally: 
    无论有无异常发生都会执行的代码块
```

在不符合Python解释器的语法或逻辑规则时，是由Python解释器主动触发的各种类型的异常，而对于违反程序员自定制的各类规则，则需要由程序员自己来明确地触发异常，这就用到了raise语句，raise后必须是一个异常的类或者是异常的实例

```python
raise TypeError('name must be str')
```

我们可以通过继承内置的异常类来自定义异常类

```python
class MyException(BaseException):
    def __init__(self,msg):
        self.msg=msg
    def __str__(self):
        return self.msg

try:
    raise MyException('类型错误')
except MyException as e:
    print(e)
```

### 4. 断言

Python assert 语句，又称断言语句，可以看做是功能缩小版的 if 语句，它用于判断某个表达式的值，如果值为真，则程序可以继续往下执行；反之，Python 解释器会报 AssertionError 错误。

assert 会令程序崩溃，为什么还要使用它呢？这是因为，与其让程序在晚些时候崩溃，不如在错误条件出现时，就直接让程序崩溃，这有利于我们对程序排错，提高程序的健壮性。因此，assert 语句通常用于检查用户的输入是否符合规定，还经常用作程序初期测试和调试过程中的辅助工具。

```python
mathmark = int(input())
# 断言数学考试分数是否位于正常范围内
assert 0 <= mathmark <= 100
#只有当 mathmark 位于 [0,100]范围内，程序才会继续执行
print("数学考试分数为：",mathmark)
```



## 2. 反射

反射，提供了一种更加灵活的方式让你可以实现去对象中操作成员

```python
class Person(object):
    def __init__(self,name,wx):
        self.name = name
        self.wx = wx
	
    def show(self):
        message = "姓名{}，微信：{}".format(self.name,self.wx)
```

Python中提供了4个内置函数来支持反射：

- getattr，去对象中获取成员

    ```python
    v1 = getattr(对象,"成员名称")
    v2 = getattr(对象,"成员名称", 不存在时的默认值)
    ```

- setattr，去对象中设置成员

    ```python
    setattr(对象,"成员名称",值)
    ```

- hasattr，对象中是否包含成员

    ```python
    v1 = hasattr(对象,"成员名称") # True/False
    ```

- delattr，删除对象中的成员

    ```python
    delattr(对象,"成员名称")
    ```

以后如果再遇到 对象.成员 这种编写方式时，均可以基于反射来实现。

```python
class Account(object):
    def login(self):
        pass

    def register(self):
        pass

    def index(self):
        pass

    
def run(self):
    name = input("请输入要执行的方法名称：") 
    account_object = Account()
    method = getattr(account_object, name,None)

    if not method:
        print("输入错误")
        return 
    method()
```

在Python中有这么句话：一切皆对象。反射支持以字符串的形式去对象中操作成员【等价于 对象.成员 】，所以，基于反射也可以对类、模块中的成员进行操作。